### ISSUE TITLE
Tasks for DGC migration

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#260]
* [ ] List docs staying on DCC and the docs being moved.
* [ ] Look over documentation on CodeMirror usage (particularly in sources panel) to check for any powerful updates from the CM4 update that should be included. Ref Issue #209 
* [ ] Make sure Promises panel stuff is documented.
* [ ] Service Worker tooling docs
* [ ] Cover new Network panel timeline view.
    * Quick overview of the entire load history.
    * Select specific timeframe to view resources for.
    * Just plain awesome.

**Comment by Meggin** [comment]
Are new tools coming out for Service Workers? We will need to track and document these (43).

**Comment by Garbee** [comment]
Added SW stuff to be documented. Also the other day I went ahead and added Promises panel to this list. Since it is moving to ship shortly, it is still 12 or 18 weeks out of actually being stable. So it can probably just wait and the content can land on DGC first instead of DCC.
